### ISSUE TITLE
Is there a way to obtain column names in results after executing a query?....

### ISSUE THREAD

**Issue by yezyilomo** [cyberdelia/flask-mysql#27]
Well I was wondering if it's possible to obtain column names after executing a query just like the way I obtain results from a cursor after executing a query, ie
cursor.execute('certain sql statement')
cursor.fetchall()    this is for obtaining all results
cursor.getcolumns()   this is what am asking if it's possible to do

For example I just want to be able to get Reg_No, First_Name, Last_Name and Course from a certain query executed and  give results as shown in a picture below.
![db_table](https://user-images.githubusercontent.com/20328561/31088211-8149f434-a7a8-11e7-9ce4-bc7d96420326.png)

**Comment by GeneralTyres** [comment]
You can call the following query, it will return ONLY the column names:
SELECT column_name from information_schema.columns where table_schema = "your_database_name" and table_name = "your_table_name";

Remember because flask-MySQL is built on PyMySQL you can essensially use all the functions available in PyMySQL like:
cursor.query('some query')

I know this is not exactly your workflow but its a start.

**Comment by yezyilomo** [comment]
Thanks for the support, I've found a way to do it, it appears that a cursor has attribute called 'description' which when accessed after executing a query it gives column names  of query result!..

**Comment by GeneralTyres** [comment]
Ah cool. Thanks for posting the solution
